apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: twilio
  namespace: restaurant
  # namespace: monitoring-tools
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: "twilio.trysimmer.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: twilio
                port:
                  number: 80