# apiVersion: v1
# kind: Service
# metadata:
#   name: twiliosand
#   labels:
#     app: twiliosand
# spec:
#   type: LoadBalancer
#   ports:
#     - name: twiliosand
#       port: 80
#       targetPort: 5000
#   selector:
#     app: twiliosand

apiVersion: v1
kind: Service
metadata:
  name: twiliosand
  labels:
    app: twiliosand
spec:
  type: NodePort
  ports:
    - name: twiliosand
      port: 80
      targetPort: 5000
      nodePort: 30091  # Specify the desired nodePort value here
  selector:
    app: twiliosand
